{{- if and .Values.grafana.enabled .Values.grafana.admin.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.grafana.admin.existingSecret | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: qlack-lgtm-grafana-admin
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | quote }}
type: Opaque
stringData:
  {{ .Values.grafana.admin.userKey | quote }}: {{ .Values.grafana.admin.username | quote }}
  {{ .Values.grafana.admin.passwordKey | quote }}: {{ required "grafana.admin.password must be set when grafana.admin.create=true" .Values.grafana.admin.password | quote }}
{{- end }}

