apiVersion: v2
name: qlack-lgtm
description: A Helm chart that installs QLACK LGTM components including OpenTelemetry Collector, Grafana Loki, Grafana Mimir, Grafana Tempo, and Grafana for monitoring and visualization.
type: application
version: 0.0.4 # This is the version of the Helm chart itself. It should be incremented whenever there are changes to the chart, such as updates to dependencies or configuration.
appVersion: "0.0.4" # This is the version of the application being deployed. It should be updated to reflect the version of QLACK LGTM that is being installed.
maintainers:
  - name: European Dynamics SA
    url: https://www.eurodyn.com

dependencies:
    - name: opentelemetry-collector
      version: "0.158.0"
      repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
      alias: otelCollector
      condition: otelCollector.enabled
    - name: loki
      version: "16.0.0"
      repository: "oci://ghcr.io/grafana-community/helm-charts"
      condition: loki.enabled
    - name: mimir-distributed
      version: "6.0.6"
      repository: "https://grafana.github.io/helm-charts"
      alias: mimir
      condition: mimir.enabled
    - name: tempo
      version: "2.2.0"
      repository: "oci://ghcr.io/grafana-community/helm-charts"
      condition: tempo.enabled
    - name: grafana
      version: "12.4.1"
      repository: "oci://ghcr.io/grafana-community/helm-charts"
      condition: grafana.enabled